### ISSUE TITLE
Peter wants to easily add gifs to retro items

### ISSUE THREAD

**Issue by liamdarmody** [pivotal/postfacto#106]
As Peter 
I want the ability to easily add a giphy to retro items
So that I can communicate more emotion in the items that I add

---

**ACCEPTANCE**

**GIVEN** I am adding a new retro item
**WHEN** I type '/giphy [keyword* in the input field
**AND** click submit
**THEN** a retro item is posted with a relevant gif

---

**NOTES**

- https://developers.giphy.com/

**Comment by crswty** [comment]
I would be concerned about having to view that gif repeating for the remainder of the retro...

**Comment by jgalilee** [comment]
What's the syntax here for writing a giphy gif? I have one working with "This is my retro item /giphy rad check out this rad gif!" where (/giphy rad) is replaced by a image to the first gif associated with 'rad'

**Comment by liamdarmody** [comment]
As referenced in #117, we decided not to merge this feature into **master**. We may revisit this in the future but have decided to park it for now.
