### ISSUE TITLE
Heroku deploy doesn't allow users to log in to retros

### ISSUE THREAD

**Issue by cassiodias** [pivotal/postfacto#120]
hello! I am not sure if that's the best place for asking for help... I have installed on Heroku following the deploy.sh process... all good, ran smoothly.

I am creating a public retro and whenever I click on menu (dashboard) I am being redirected to /login

same happens when archiving the retro... just jump to /login and when going back to the retro, nothing has been archived.

have you seen anything like that?

Using the latest release.

thanks!

**Comment by seadowg** [comment]
Hey @cassiodias 👋

This is intended. You need to "login" to the retro with the password to archive it or change any settings. Does that make sense?

**Comment by cassiodias** [comment]
which password? the default admin or the password to the retro?

I added the password to the retro and also removed it... both cases get the same behavior.

For instance: https://imc-retro-board.herokuapp.com/retros/march-1 - has no password... after clicking on archive or retro setting, goes to login... the config page pops up quickly and moves to login

This one has password: https://imc-retro-board.herokuapp.com/retros/slug-name/ 
passwd: password

**Comment by seadowg** [comment]
> which password? the default admin or the password to the retro?

The password for the retro. I can see that the copy on the password screen isn't entirely clear there.

> I added the password to the retro and also removed it... both cases get the same behavior.

Ah. So I believe the confusing thing here is being able to create a retro without a password. This is only possible from the admin dashboard which wasn't typically used before (the OAuth login was generally the standard). I think the change we should make is to require a password to create a retro. How does that sound to you?

**Comment by seadowg** [comment]
@cassiodias did my answer help?

**Comment by cassiodias** [comment]
I have created again a new postfacto instance on heroku (latest version).

Created a second admin user; logged as new admin with to make sure it's not a default user problem. With the new admin user, I have created a new private retro with the password: 1234. 

Then going to the retro page, after informing the 1234 passwd, the login doesn't work.

Is that the right flow?

**Comment by seadowg** [comment]
That flow should work. Are you able to log into the retro from a different browser session?

**Comment by cassiodias** [comment]
Tried from safari and chrome

**Comment by cassiodias** [comment]
getting 403

**Comment by cassiodias** [comment]
should it be a heroku problem?

**Comment by seadowg** [comment]
Not that I am aware of. I'll walk through your steps to double check
everything when I get a chance. Are you using 3.0.0?

**Comment by bu3** [comment]
Hi @seadowg ,

I'm Fabio from the Pivotal Dublin office. 
I'm now working with @cassiodias and we are trying to setup our Postfacto instance.
I tried to install it on my own and I have the same strange behaviour that @cassiodias described.

I managed to create a Retro in the Admin panel then when I try to login in the Retro it seems to be successful showing the dashboard for a sec but then it goes back to the login page.

It's strange because the API return 403.
If you want to take a look to it follow this link: https://my-postfacto-web.herokuapp.com/retros/fabio

Cheers

**Comment by seadowg** [comment]
Ok so I went through these steps:

1. Download Postfacto 3.0.0 from https://github.com/pivotal/postfacto/releases/tag/3.0.0
1. Unzip and `cd` into `package/heroku`
1. Deploy using `./deploy.sh my-postfacto my-postfacto-api`
1. Go to the admin dashboard and create a retro with a password
1. Go to the retro and login using my password
1. I see the login page again (and the API response for the retro details is a 403)

Looks like it's a problem with the Heroku deploy!

**Comment by seadowg** [comment]
So it looks like the Heroku deploy sets the `SESSION_TIME` to `""` which ends up giving the auth tokens a session time of 0 seconds. 

@cassiodias and @bu3 could you verify that this is also happening for yourselves? To double check run the following:

```bash
> heroku console -a <api-app-name>
irb(main):001:0> Rails.application.config.session_time
```

You should see an output of `0 seconds`

**Comment by cassiodias** [comment]
Yeap, that's zero.

**Comment by cassiodias** [comment]
what's the default number or string value?

**Comment by seadowg** [comment]
@cassiodias it's a problem with the the API parsing the blank string as 0 rather than ignoring the configuration. I'm fixing it at the moment 😁

**Comment by seadowg** [comment]
Ok fixed and putting the release together now

**Comment by seadowg** [comment]
@cassiodias @bu3 new release out now: https://github.com/pivotal/postfacto/releases/tag/3.0.1

**Comment by cassiodias** [comment]
Awesome! Thanks man!

**Comment by bu3** [comment]
Thanks mate!

**Comment by cassiodias** [comment]
It works perfectly now ;)

**Comment by PorasPete** [comment]
Hello, I've deployed Postfacto to cloud foundry but unable to access admin dashboard, getting error invalid email or password, both using my custom email or default ones. During deployment, I used ADMIN_EMAIL=my-email@email.com ADMIN_PASSWORD=xyz ./deploy.sh my-retro-app, deployment was successful but I received message 
Incorrect Usage: unexpected argument "ADMIN_EMAIL=my-email@email.com ADMIN_PASSWORD=xyz rake admin:create_user"
FAILED  
Please advise, thanks
