### ISSUE TITLE
Use of sed in deploy.sh is mac-specific

### ISSUE THREAD

**Issue by RoboMWM** [pivotal/postfacto#133]
https://github.com/pivotal/postfacto/blob/94ca63b2c48b2d02cd38935b95597875016bc78f/deployment/deploy-cf.sh#L20

The `-i` switch used here is mac OS-specific, and fails on linux as it tries to find an empty file given the `''` value.

Either need to do OS detection in script, or use something other than sed.

- https://stackoverflow.com/a/43453459
- https://github.com/despark/kohana/commit/656e1f75e41520d678af8c0001b09e1d9a774527

**Comment by textbook** [comment]
The latest version ([3.2.0](https://github.com/pivotal/postfacto/releases/tag/3.2.0)) no longer uses `sed -i` in the deploy scripts, we've switched to:

```bash
sed \
  -e "s/{{api-app-name}}/${API_HOST}/" \
  -e "s/{{pcf-url}}/${APP_DOMAIN}/" \
  <"$CONFIG_DIR"/config.js \
  >"$ASSETS_DIR"/web/config.js
```

I've just tested this in Ubuntu 18.04 and it seems to work fine!
