### ISSUE TITLE
Ruby version 2.6.1 not found

### ISSUE THREAD

**Issue by RoboMWM** [pivotal/postfacto#138]
Due to https://github.com/cloudfoundry/ruby-buildpack/commit/fca8745a185fc09760cf848f91b72c128a1ec661 Ruby 2.6.1 no longer exists. Changing the version in the `Gemfile` to 2.6.3 seems to be working fine.

**Comment by textbook** [comment]
We're working on getting that update to Ruby shipped. In the meantime, you can pin the buildpack: `https://github.com/cloudfoundry/ruby-buildpack.git#v1.7.37` is the last version that has 2.6.1.
