### ISSUE TITLE
Alex can setup Postfacto for Heroku

### ISSUE THREAD

**Issue by seadowg** [pivotal/postfacto#14]

**Comment by nickrivadeneira** [comment]
Is Heroku deployment possible with Postfacto out-of-the-box?

**Comment by seadowg** [comment]
@nickrivadeneira I don't think it'll just work out of the box. Two things to solve off the top of my head are:

* Redis configuration assumes a Cloud Foundry environment (https://github.com/Pivotal/postfacto/blob/master/api/config/cable.yml)
* Need a static buildpack for Heroku (there is an unofficial one I believe).

My plan for this was to let the `api` serve `web` to make the whole thing a lot simpler. Let me know if you give it a go as it would be great to have a PR that gets us a step closer to this!
