### ISSUE TITLE
PWS: frontend and backend cannot connect because of CORS

### ISSUE THREAD

**Issue by MohamedAbubackerSiddiq** [pivotal/postfacto#142]
I have pushed both the API and Web to the PWS. The Web (frontend) cannot able to connect to the API (backend) because of CORS. How to enable CORS or open container to container communication in PWS

**Comment by tom025** [comment]
Check that env var `CLIENT_ORIGIN` is set correctly on the api application. You can see this with `cf env APP_NAME`.

**Comment by crswty** [comment]
This has come up a few times now, I think we should change the default deployment (at least for CF) to use context path routing so both the web and the API are served from the same domain. This should mean less manual configuration and we can keep the option to set permissible CORS origins for other deployment topologies.

**Comment by MohamedAbubackerSiddiq** [comment]
Hi,

That would be a good addition by default.

**Comment by tom025** [comment]
I agree that this should be improved.

@crswty I like your idea of using context path routing. I would like to explore that idea further.

Another solution that I discussed with @seadowg was embedding the client into the api so it could be served statically from the same domain. I like this idea as it reduces the number of artifacts to deploy and removes the need to configure CORS. This may be tricky to implement with how the application is currently structured.

I propose changing the default deployment to have the following routes based on a given `app-name`:

| App Name    | Route                           |
|-------------|---------------------------------|
|app-name-api | https://app-name.somecf.com/api |
|app-name-web | https://app-name.somecf.com/web |

PRs and feedback welcome.

**Comment by crswty** [comment]
I think that the proposed change means we won't need to tell the front end where the api is so should also fix https://github.com/pivotal/postfacto/issues/133

**Comment by textbook** [comment]
The new, single-artifact default deployment topology (available from version 4.0.0) means that CORS issues are no longer a problem - the backend serves the frontend, which uses relative routes, so the requests are not cross domain.
