### ISSUE TITLE
Replace p-flux with redux

### ISSUE THREAD

**Issue by tom025** [pivotal/postfacto#155]
See [architecture-decisions/0002-replace-p-flux-with-redux.md](../blob/master/architecture-decisions/0002-replace-p-flux-with-redux.md)

**Comment by crswty** [comment]
#161 Has moved the state from PUI cursor into Redux store and connected it back into the components which was the first big step for this. We are now in a good position to be replacing the static Action calls with Redux (mapDispatchToProps) triggered events.

I suggest we keep this open as a long running issue to track those ongoing changes against.

**Comment by crswty** [comment]
As of https://github.com/pivotal/postfacto/pull/168/commits/0fc6028f9b965c3c857eb31a9a2ef56812dd9795 in #168 p-flux and pui-cursor are now removed in favour of Redux
