### ISSUE TITLE
Investigate if it is possible to run 2 dynos from Heroku 1-click deploy

### ISSUE THREAD

**Issue by tom025** [pivotal/postfacto#157]
In order to provide a heroku one click deploy from readme we need to determine if we can condense the current deployment into one application or if we can deploy 2 apps from one click.

To consider:
  * Is it possible to get heroku to define two applications to deploy from a 1-click?
  * Does heroku support [context path routing](https://docs.cloudfoundry.org/devguide/deploy-apps/routes-domains.html) like CF?
  * Is it possible to run two applications on single dyno? Is it undesirable to do that?
  * Should we get the API to serve the client?

**Comment by crswty** [comment]
I was planning on writing up an ADR proposal to support moving towards shipping a single app.

Currently the complexity of two apps causes pain on [cf](https://github.com/pivotal/postfacto/issues/142) and [k8s](https://github.com/pivotal/postfacto/issues/115) as well.

Having the separation would be nice in the case where we may want to scale them independently but given the probable sizes of most deployments I would suggest this is unlikely to add much benefit to most users. We may want to revisit this if someone wants to host a large scale instance in the future but that those problems at that scale should probably really be solved with a CDN on similar.

**Comment by crswty** [comment]
Afterthought: I would also be happy to review an ADR if someone else has time to put it together.

**Comment by tom025** [comment]
> Is it possible to get heroku to define two applications to deploy from a 1-click?

https://devcenter.heroku.com/articles/heroku-button does not mention this as a posibility anywhere. Also an [app.json](https://devcenter.heroku.com/articles/app-json-schema) file only defines one app at a time. 

> Does heroku support context path routing like CF?

Not according to https://devcenter.heroku.com/articles/http-routing

> Is it possible to run two applications on single dyno? Is it undesirable to do that

https://medium.com/@nadayar/heroku-fu-multiple-servers-on-one-dyno-6fc68d57b373 does show that it is possible but I think it is undesirable.

I think based on this we should start planning to reduce the application down to one deployment. @crswty I am happy to start an ADR for that.
