### ISSUE TITLE
Unable to deploy postfacto

### ISSUE THREAD

**Issue by benlachman** [pivotal/postfacto#167]
I'm trying to get postfacto deployed by any simple means. Currently I've tried two methods: 
1. Deploy to Heroku
2. Deploy as a docker container using dokku on a Linode.

For 1. The instructions seem pretty simple.

Expected result: Following the deploy instructions yield a deployed Heroku instance of postfacto:

Actual results: 
1. `./deploy.sh` referenced in the instructions doesn't exist. 
2. `./deploy-heroku.sh` has the wrong permissions to run (easily fixed).
3. `./deploy-heroku.sh` expects subdirectories of the `deployment/heroku` directory to be in the same directories as it is.
4. `./deploy-heroku.sh` expects to be in the root directory of the repository
5. After running `./deploy-heroku.sh` in the root directory, a deploy fails with the error: `App not compatible with buildpack: https://github.com/heroku/heroku-buildpack-ruby.git#v200`

(For 2, there is no documentation at all and it's unclear how the Dockerfile is actually supposed to be used and is missing a CMD line…)

Any pointers on how to get this up and running on Heroku?

**Comment by textbook** [comment]
It sounds like you're trying to deploy from the source code, not the actual release package. Download the `package.zip` from [the latest release](https://github.com/pivotal/postfacto/releases/tag/3.2.0) and try that.

**Comment by benlachman** [comment]
Thanks! This was super helpful. I don't think I've ever run across a repo that (intentionally) isn't deployable by cloning it, but that you have to package it first, then extract and deploy it.

**Comment by benlachman** [comment]
@textbook I created a PR with a super small edit to the README to make this less likely to waste your time in the future 😉
