### ISSUE TITLE
Containerize postfacto

### ISSUE THREAD

**Issue by crswty** [pivotal/postfacto#191]
Once we have made the app deployable as a single artefact, we can Containerize it to make it available to more platforms (i.e. kubernetes)

Steps
- [x] Dockerfile to build
- [ ] Push to dockerhub in pipeline

Requires:
https://github.com/pivotal/postfacto/pull/174

Enables:
https://github.com/pivotal/postfacto/issues/115

**Comment by crswty** [comment]
With regards to the current images & tags, I plan on repurposing postfacto/postfacto as the actual built artefact and keep postfacto/dev as the dev container. I will also delete postfacto/ping

@seadowg I think you are the most likely person to be affected by this so shout if you see a problem.

**Comment by sapient007** [comment]
be awesome if the project can consider a helm deploy of postfacto

**Comment by crswty** [comment]
Totally agree, we're actually tracking that in https://github.com/pivotal/postfacto/issues/115 and I have a draft PR here: https://github.com/pivotal/postfacto/pull/197

Are you interested in testing a beta version once we've sorted out packaging and releasing?

**Comment by crswty** [comment]
We released an image ready for testing/feedback in [4.1.0](https://github.com/pivotal/postfacto/releases/tag/4.1.0). Available on dockerhub at [postfacto/postfacto](https://hub.docker.com/r/postfacto/postfacto)
