### ISSUE TITLE
Scroll does not work in Chrome on Windows 10

### ISSUE THREAD

**Issue by exosyphon-meritize** [pivotal/postfacto#210]
Clicking a card scrolls out of view on Windows 10. This is pretty frustrating because the presenter clicks on a card then has to scroll back down to see what was actually clicked.

**Comment by textbook** [comment]
I've tried to recreate this in a Windows 10 VM, but Chrome 79 seems to scroll to the right places; could you provide any more information to help recreate this issue?

**Comment by j-lea** [comment]
Closing as we are still unable to recreate this issue. Please reopen if the problem persists
