### ISSUE TITLE
Broken Init

### ISSUE THREAD

**Issue by jared-schmidt-civ** [pivotal/postfacto#250]
While trying to deploy the postfacto helm chart from scratch, I found that the chart is deploying an init container that tries to connect to the postgresql container before the postgresql container has been started.

**Comment by th3n3rd** [comment]
That is not an issue, the init container is there to "wait" until postgres is ready to accept connections.

**Comment by jared-schmidt-civ** [comment]
The problem is that the other containers appear to be waiting for the init container to finish before starting, so they are deadlocked.

**Comment by textbook** [comment]
I guess you're talking about the one that runs [this command][1]:

    ["sh", "-c", "for i in {1..33}; do sleep 3; if PGPASSWORD=$POSTGRESQL_PASSWORD psql -h {{ .Release.Name }}-postgresql -U {{ .Values.postgresql.postgresqlUsername }}; then exit 0; fi; done; exit 1"]



  [1]: https://github.com/pivotal/postfacto/blob/b156a1b71185481f523fae6295d7c8236a60d798/deployment/helm/templates/deployment.yaml#L63

**Comment by jared-schmidt-civ** [comment]
Yes, that's the one.

**Comment by jared-schmidt-civ** [comment]
We didn't really do anything to config, we just followed the readme and grabbed a copy of the helm chart to see if we could get it running on a blank vanilla Kubernetes deployment.  It didn't work.

**Comment by th3n3rd** [comment]
So the init container is there to hold the postfacto container until postgres is ready to accept connections, and yeah you will see failure at the beginning because the init container will succeed as soon as postgres is reachable.

**Comment by jared-schmidt-civ** [comment]
The problem is the deadlock.  https://kubernetes.io/docs/concepts/workloads/pods/init-containers/ states that init containers run to completion before the app containers run.

**Comment by th3n3rd** [comment]
> so now we are trying to connect our storage class to it, but that is outside of the scope of this issue.

I have the feeling you expect the postfacto container to run despite postgres not being actually available to be used (i.e. volume not bound or other issues).

**Comment by jared-schmidt-civ** [comment]
If there were no deadlock, I would see errors appearing in the postgresql and redis logs, which is what happens after commenting out the init container section.

**Comment by th3n3rd** [comment]
Could you clarify what do you mean by`deadlock`, as from my point of view there there is no cycle of dependencies here.

`podContainer` waits for `initContainer` to complete
`initContainer` waits for `postgresContainer` to be ready to accept connections.

**Comment by jared-schmidt-civ** [comment]
I think I see the problem.  We aren't getting logs because with the broken storage claim connection the pod isn't even scheduling.  I thought the init container was the problem.  My bad.
