### ISSUE TITLE
Heroku deployment instructions are incorrect

### ISSUE THREAD

**Issue by deniseyu** [pivotal/postfacto#264]
Hi friends! I'm trying to set up my own instance of postfacto on Heroku and it seems like the docs have drifted quite a bit. Spinning up this issue to document what isn't working, as well as what has worked for me (assuming I can get it up and running).

Inaccuracies:

* There is no longer a `heroku/` folder
* There is no longer a `deploy.sh` script

Here's what worked:

* ...still workin on it!

Other improvements

* The deployments scripts could be committed with executable permissions
* The `assets` folder does not exist initially, and is not set up if it doesn't exist. It'd be better to ship this repo with an empty `assets` folder (or, change the script to find-or-create that folder with a path relative to the project root) so it's the relative directory requirements are clearer
* It's unclear where you're supposed to run deployment scripts from

I'm mostly just setting up this issue to track stuff for when I figure it out, but thought I'd just put it out into the open in case anyone else has already gotten this to work. I'm intending to PR this back into main later, when I get it working. Hope this doesn't come across as me complaining about the hard work y'all are doing - thanks for all the work on building and maintaining my favorite retro tool!

**Comment by textbook** [comment]
Duplicates #137 - you can't deploy from the source code, download the `package.zip` from [the latest release](https://github.com/pivotal/postfacto/releases/latest) as stated in [the README](https://github.com/pivotal/postfacto#deployment).

**Comment by textbook** [comment]
_(Also hi! 👋)_

**Comment by deniseyu** [comment]
ooof. THANK YOU. I knew I was doing something wrong. That's what I get for not reading the first line of the instructions closely. (Also, hat tip to @alex-slynko who gave me this same advice on alumni slack.)

hello! 👋🏼  hope y'all are well!
