### ISSUE TITLE
no redis dependency 

### ISSUE THREAD

**Issue by JuanFCabrera** [pivotal/postfacto#289]
hi, is there a way to deploy this without redis? we do not have redis available to us and ruby fails looking for redis during deployment.

**Comment by textbook** [comment]
The Redis dependency comes from [Action Cable](https://guides.rubyonrails.org/action_cable_overview.html) - it's used to sync the messages between multiple instances of the Ruby app, for example. We have considered investigating alternatives, as we're aware this dependency does limit deployment destinations (see e.g. #144) and is potentially unnecessary on a single-instance deployment, but right now we don't have immediate plans to do this.

**Comment by textbook** [comment]
One of my colleagues has pointed out that there is a [Postgres adapter](https://guides.rubyonrails.org/action_cable_overview.html#postgresql-adapter) (thanks @th3n3rd), so maybe it would be relatively straightforward to offer a configuration option, in the same way that you can currently use either Postgres or MySQL as the database. Would that meet your current needs? Then you'd be able to choose:

 - MySQL & Redis;
 - Postgres & Redis; or
 - Postgres only.

It's unclear when we'd have the capacity to get to it, but if anyone out there wanted to take a look and PR any documentation/configuration required we'd certainly welcome it.

**Comment by butzopower** [comment]
I've created a draft PR that switches the adapter via an environment variable.  Haven't had much of a chance to try different deployments of it, but possibly a first iteration forward to make redis optional for those using postgres.

If this works we can have a think about how we want to change deployment scripts / etc.

**Comment by JuanFCabrera** [comment]
thank you for adding this. any eta on release?

**Comment by textbook** [comment]
We just released 4.3.0 which adds an environment variable to configure this; see https://github.com/pivotal/postfacto/tree/master/deployment#from-430-removing-redis-dependency

**Comment by JuanFCabrera** [comment]
thank you for the hard work, i have tested it and found it would error in deployment as it was looking for a Redis Service defined in the manifest,yml. after commenting that out i deployed using USE_POSTGRES_FOR_ACTION_CABLE=true ./deploy <app-name> and received the error below.

   -----> Precompiling assets
          rake aborted!
          NoMethodError: undefined method `[]' for nil:NilClass
          /tmp/app/lib/configurations/redis_configuration_provider.rb:40:in `redis_config'
          /tmp/app/lib/configurations/action_cable_adapter_configuration_provider.rb:27:in `redis_adapter'
          /tmp/app/lib/configurations/action_cable_adapter_configuration_provider.rb:8:in `cable_config'
          (erb):38:in `<main>'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/railties-6.0.3.2/lib/rails/application.rb:231:in `config_for'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/actioncable-6.0.3.2/lib/action_cable/engine.rb:33:in `block (2 levels) in <class:Engine>'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/lazy_load_hooks.rb:73:in `instance_eval'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/lazy_load_hooks.rb:73:in `block in execute_hook'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/lazy_load_hooks.rb:51:in `each'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/actioncable-6.0.3.2/lib/action_cable/server/base.rb:92:in `<module:Server>'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/actioncable-6.0.3.2/lib/action_cable/server/base.rb:6:in `<module:ActionCable>'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/actioncable-6.0.3.2/lib/action_cable/server/base.rb:5:in `<top (required)>'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:23:in `require'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:23:in `require'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/actioncable-6.0.3.2/lib/action_cable.rb:52:in `server'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/actioncable-6.0.3.2/lib/action_cable/engine.rb:48:in `block (3 levels) in <class:Engine>'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/actionpack-6.0.3.2/lib/action_dispatch/routing/route_set.rb:426:in `instance_exec'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/actionpack-6.0.3.2/lib/action_dispatch/routing/route_set.rb:426:in `eval_block'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/actionpack-6.0.3.2/lib/action_dispatch/routing/route_set.rb:443:in `block in clear!'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/actionpack-6.0.3.2/lib/action_dispatch/routing/route_set.rb:443:in `each'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/actionpack-6.0.3.2/lib/action_dispatch/routing/route_set.rb:443:in `clear!'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/railties-6.0.3.2/lib/rails/application/routes_reloader.rb:35:in `block in clear!'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/railties-6.0.3.2/lib/rails/application/routes_reloader.rb:33:in `each'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/railties-6.0.3.2/lib/rails/application/routes_reloader.rb:33:in `clear!'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/railties-6.0.3.2/lib/rails/application/routes_reloader.rb:19:in `reload!'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/railties-6.0.3.2/lib/rails/application/routes_reloader.rb:29:in `block in updater'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/file_update_checker.rb:83:in `execute'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/railties-6.0.3.2/lib/rails/application/routes_reloader.rb:10:in `execute'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/railties-6.0.3.2/lib/rails/application/finisher.rb:184:in `block in <module:Finisher>'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/railties-6.0.3.2/lib/rails/initializable.rb:32:in `instance_exec'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/railties-6.0.3.2/lib/rails/initializable.rb:32:in `run'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/railties-6.0.3.2/lib/rails/initializable.rb:61:in `block in run_initializers'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/railties-6.0.3.2/lib/rails/initializable.rb:60:in `run_initializers'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/railties-6.0.3.2/lib/rails/application.rb:363:in `initialize!'
          /tmp/app/config/environment.rb:35:in `<top (required)>'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:23:in `require'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:23:in `require'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `block in require'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:291:in `load_dependency'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `require'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/railties-6.0.3.2/lib/rails/application.rb:339:in `require_environment!'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/railties-6.0.3.2/lib/rails/application.rb:523:in `block in run_tasks_blocks'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
          /tmp/contents590090709/deps/0/vendor_bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
          /tmp/contents590090709/deps/0/bundler/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `load'
          /tmp/contents590090709/deps/0/bundler/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
          /tmp/contents590090709/deps/0/bundler/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:28:in `run'
          /tmp/contents590090709/deps/0/bundler/gems/bundler-1.17.3/lib/bundler/cli.rb:463:in `exec'
          /tmp/contents590090709/deps/0/bundler/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
          /tmp/contents590090709/deps/0/bundler/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
          /tmp/contents590090709/deps/0/bundler/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
          /tmp/contents590090709/deps/0/bundler/gems/bundler-1.17.3/lib/bundler/cli.rb:27:in `dispatch'
          /tmp/contents590090709/deps/0/bundler/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
          /tmp/contents590090709/deps/0/bundler/gems/bundler-1.17.3/lib/bundler/cli.rb:18:in `start'
          /tmp/contents590090709/deps/0/bundler/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
          /tmp/contents590090709/deps/0/bundler/gems/bundler-1.17.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
          /tmp/contents590090709/deps/0/bundler/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
          /tmp/contents590090709/deps/0/bin/bundle:104:in `load'
          /tmp/contents590090709/deps/0/bin/bundle:104:in `<main>'
          Tasks: TOP => environment
          (See full trace by running task with --trace)
          **ERROR** Error precompiling assets: exit status 1
Error staging application: App staging failed in the buildpack compile phase
FAILED

**Comment by butzopower** [comment]
Hi @JuanFCabrera 

This might be a bit of discrepancy with the deployment docs (so thanks for some quick feedback!).  `USE_POSTGRES_FOR_ACTION_CABLE` is actually needed for the running application, not when you run the deploy script.

Can you try adding it at the bottom of the `manifest.yml`.  So change:

```
  env:
    WEBSOCKET_PORT: 443
    SESSION_TIME: ((session-time))
```

to

```
  env:
    WEBSOCKET_PORT: 443
    SESSION_TIME: ((session-time))
    USE_POSTGRES_FOR_ACTION_CABLE: true
```

**Comment by JuanFCabrera** [comment]
That worked perfectly. Thank you.
