### ISSUE TITLE
Add analytics around sharing/visiting retros via Magic Link

### ISSUE THREAD

**Issue by j-lea** [pivotal/postfacto#291]
#288 introduced a new feature around sharing private retros via a "Magic Link".

To know if/how people are using this feature, we need to add analytics. Postfacto currently uses Mixpanel for analytics, and things currently tracked can be found [here](https://github.com/pivotal/postfacto/blob/master/web/src/redux/actions/analytics_actions.js)

**Magic link events to track (including but not limited to):**
- Viewed magic link (click on 'Share')
- Copied magic link (via copy to clipboard in the modal)
- Retro visited via magic link
- Share link turned on for a retro
- Share link turned off for a retro

**Comment by butzopower** [comment]
@j-lea Can we close this now that the #294 has been merged?

**Comment by textbook** [comment]
I believe we've only covered some of the cases:

 - [x] Viewed magic link (click on 'Share')
 - [x] Copied magic link (via copy to clipboard in the modal)
 - [x] Retro visited via magic link
 - [ ] Share link turned on for a retro
 - [ ] Share link turned off for a retro

The latter require analytics being sent from the server, which we haven't done at all yet, so I'd be up for closing this and splitting them out to a separate task.

**Comment by j-lea** [comment]
Yes I can create the separate task for that
