### ISSUE TITLE
Postfacto health check

### ISSUE THREAD

**Issue by mimozell** [pivotal/postfacto#325]
Hi,

I'm looking for a health check endpoint, but I can't find any. I'm not familiar with Ruby, but found only one occurrence of `health` in the project and that was in the Terms page. None of the controllers seemed to have such an endpoint either. Is there some way to query the health of the app? I'm looking for something simple, that returns 200 when invoked and the app is healthy.

**Comment by textbook** [comment]
I'd recommend looking at the Helm setup if you're trying to run Postfacto in a K8s or similar container environment. In this case they're referred to as "probes", and the root path (which just returns the `index.html` for the SPA) can be used:

https://github.com/pivotal/postfacto/blob/fc775053346b22e9fadbe9ab863baf94fc1cabad/deployment/helm/templates/deployment.yaml#L91-L102

**Comment by mimozell** [comment]
Thanks, root worked. I had a lot of issues with this though and mainly because the app itself was redirecting to https while the load balancer was talking to it on HTTP and always receiving a 301 for no apparent reason. Once I disabled the SSL redirect the load balancer was finally able to mark the app as healthy. I wish you guys had documentation on your Docker image :/. Anything more than a blank page would help.
