### ISSUE TITLE
custom dns on Heroku

### ISSUE THREAD

**Issue by mshahat** [pivotal/postfacto#333]
Hello Team, 

I've successfully deployed postfacto v4.3.0 on heroku.
I'm not using Google authentication. 

I've changed a couple of things, I'd like to know your feedback as well. 
1. changed the region to `eu`
2. add `--stack heroku18` to the `heroku create app` command, as I received an error

I'd like to use a custom dns to reach my app at  *postfacto.mydomain.com* 

is that possible with heroku hobby-dev tier? when I added my dns, it doesn't seem to work. 

Thanks,

**Comment by textbook** [comment]
The [Heroku docs](https://devcenter.heroku.com/articles/custom-domains) suggest you should be able to set a custom domain on any tier as long as the account is verified:

> You can add custom domains to any Heroku app. Adding domains does not incur extra charges. For security purposes, you must [verify your Heroku account](https://devcenter.heroku.com/articles/account-verification) to add domains to apps.

That said I haven't tried it myself; you might be best off raising with their support, I think it's out of scope for the app itself.

**Comment by mshahat** [comment]
Thanks @textbook for the feedback. 

I was able to get it working after upgrading to hobby tier and applying Automated certificate management, the free tier does not help with https for custom domains

Many thanks
