### ISSUE TITLE
Redis dependency for v4.3.0

### ISSUE THREAD

**Issue by mshahat** [pivotal/postfacto#334]
Hello, 

in the deployment doc it's mentioned that redis is no more needed if postgresql is used. 
is this applicable on v4.3.0? or only for future releases e.g. when 4.4 is released? 

Thanks,

**Comment by textbook** [comment]
You can opt-in to use of Postgres for ActionCable, instead of Redis, from 4.3.0: https://github.com/pivotal/postfacto/tree/master/deployment#from-430-removing-redis-dependency

**Comment by mshahat** [comment]
Thanks @textbook , will try that today. 

Any implications positive or not when I don't use redis ? 

Thanks

**Comment by textbook** [comment]
Honestly, at this point we don't know. The biggest and most-used instances we're aware of all use the Redis option, as exposing the Postgres adapter is a relatively new feature for Postfacto. [The docs](https://guides.rubyonrails.org/action_cable_overview.html#adapter-configuration) don't suggest any issues, and we're considering making it the default for Heroku (so folks can deploy to the free tier without even verifying their account). I think it should be possible to switch back over to Redis if you do see any problems, though; just remove the `USE_POSTGRES_FOR_ACTION_CABLE` env var (or set it to `false`), supply a `REDIS_URL` and restart the app.

**Comment by mshahat** [comment]
thanks @textbook !
