### ISSUE TITLE
Update Ruby Version and new release

### ISSUE THREAD

**Issue by dwettstein** [pivotal/postfacto#352]
Currently, Postfacto uses Ruby version 2.6.3, which was released on 2019-04-17. As the 2.6 releases will be EOL soon, it should be updated to version 2.7.x.
Additionally, the latest stack on Heroku (heroku-20) doesn't support Ruby 2.6.3 anymore.

BTW, when do you plan to release a new (bugfix) version of Postfacto with updated dependencies?
At the moment, it is a bit cumbersome to deploy it, due to the dependency to _mimemagic_. Ruby on Rails version 6.0.3.6 doesn't depend on _mimemagic_ anymore, and an update to that release works without additional efforts (tested using dev docker).

Related issues:
- https://github.com/pivotal/postfacto/issues/349
- https://github.com/pivotal/postfacto/issues/351
- https://github.com/rails/rails/issues/41750

Thanks and cheers!

**Comment by textbook** [comment]
Closing this out as it's already covered by the issues you link

**Comment by dwettstein** [comment]
Hey @textbook
OK, that's fine. So when can we expect a new (fixed) release of Postfacto?
Thanks and cheers.

**Comment by textbook** [comment]
Fixed in v4.3.1
