### ISSUE TITLE
offline version

### ISSUE THREAD

**Issue by bbodenmiller** [pivotal/postfacto#358]
Would be nice if an offline version was available that included all necessary Gems already. In some cases it's desired to run this offline without reaching out to RubyGems service.

**Comment by textbook** [comment]
It's not well (at all?) documented, but there is a Docker image: https://hub.docker.com/r/postfacto/postfacto/

**Comment by bbodenmiller** [comment]
@textbook thanks. I'm wanting to run on core l cloud foundry.

**Comment by textbook** [comment]
That might not prevent you, if Docker's enabled on your foundation: https://docs.cloudfoundry.org/devguide/deploy-apps/push-docker.html

**Comment by textbook** [comment]
I did notice while migrating to GitHub Actions that the Ruby setup action was including dependencies in the package, which got me investigating this. I don't have access to an environment to test it, but I think the **Package (including dependencies)** on https://github.com/pivotal/postfacto/actions/runs/793859568 might work if you're still looking for this.

**Comment by bbodenmiller** [comment]
Believe fixed by https://github.com/pivotal/postfacto/pull/363.
