### ISSUE TITLE
Need to host postfacto on azure 

### ISSUE THREAD

**Issue by maulinshah-cmd** [pivotal/postfacto#417]
I hosted postfacto on the azure virtual machine using docker image however application going to stop simultaneously. So provide me solution to not going it in stop state or any other way to host postfacto instead of docker Image.

Thanks & Regards.
Maulin

**Comment by textbook** [comment]
It's hard to provide a solution without more information about what the problem might be - I'd suggest looking into the logs coming from the application at startup to see if they contain any clues. You can see the supported deployment paths on https://github.com/pivotal/postfacto/tree/master/deployment.

**Comment by maulinshah-cmd** [comment]
> It's hard to provide a solution without more information about what the problem might be - I'd suggest looking into the logs coming from the application at startup to see if they contain any clues. You can see the supported deployment paths on https://github.com/pivotal/postfacto/tree/master/deployment.

@textbook  I have hosted postfacto on docker desktop and container going in an Exited state so it results in application Stop. Can you please provide me solution for the postfacto services going to stop state.

Regards,
Maulin
Can

**Comment by textbook** [comment]
> Can you please provide me solution for the why postfacto services going to stop state.

Still not without more information, at least:

- Which image you're pulling (latest is `postfacto/postfacto:4.3.11` per https://hub.docker.com/r/postfacto/postfacto);
- How you're starting it (including the configuration you're using to set the database, etc.); and
- What the outputs are (assuming you're using the right image, the logs should tell you why it's stopping).

**Comment by maulinshah-cmd** [comment]
> > Can you please provide me solution for the why postfacto services going to stop state.
> 
> Still not without more information, at least:
> 
> * Which image you're pulling (latest is `postfacto/postfacto:4.3.11` per https://hub.docker.com/r/postfacto/postfacto);
> * How you're starting it (including the configuration you're using to set the database, etc.); and
> * What the outputs are (assuming you're using the right image, the logs should tell you why it's stopping).

Hi @textbook 
as i Checked in run.sh file following version i'm currently using: **postfacto/dev:2.7.3-14.16.1**
I am starting it using by CLI of Docker using run.sh command
I am getting expected output .
Where i can get specific logs of postfacto.

Regards,
Maulin

**Comment by textbook** [comment]
You're running the wrong container. `postfacto/dev` provides the development environment, so you can work on Postfacto without having to install the specific versions of e.g. Node, Ruby yourself (see https://github.com/pivotal/postfacto/blob/master/CONTRIBUTING.md). To run Postfacto in production, use `postfacto/postfacto`.

**Comment by maulinshah-cmd** [comment]
> You're running the wrong container. `postfacto/dev` provides the development environment, so you can work on Postfacto without having to install the specific versions of e.g. Node, Ruby yourself (see https://github.com/pivotal/postfacto/blob/master/CONTRIBUTING.md). To run Postfacto in production, use `postfacto/postfacto`.

Where i can check logs?

**Comment by textbook** [comment]
That's a matter of the platform you're using, not Postfacto itself, but see e.g. https://docs.microsoft.com/en-us/azure/container-instances/container-instances-get-logs.
