### ISSUE TITLE
Alex cannot finish deploying postfacto

### ISSUE THREAD

**Issue by samuelt1** [Pivotal/postfacto#61]
When Alex follows the deployment procedure for PWS
He gets stopped at the last step of the deployment procedure, and can progress no further.
Alex made sure that he followed every step, step by step.
Alex also got frustrated enough to make a brand new PWS account just to test out this one thing.

Alex made a retro at: 
http://fresh-postfacto.cfapps.io/retros/tech
see for yourself the 406 error.

If you want to enter the admin console to see what is up there go ahead!
Alex was kind enough to leave all the default passwords in there so feel free to poke around.

Note:
Alex also gets a strange message after running deploy.sh

Task has been submitted successfully for execution.
task name:   6850fc82
task id:     3
~/projects/postfacto/web ~/projects/postfacto
[10:06:09] Local gulp not found in ~/projects/postfacto/web
[10:06:09] Try running: npm install gulp

If you have ANY questions feel free to PM Alex (me).

(after digging into it, Alex thinks it have something to do with not running any build, set up code like gulp. Alex went into the web folder then ran npm install a few times, there are a few issues there, but he fixed them. gulp package fails because the public/index.html file does not exist. Running gulp fails)

**Comment by seadowg** [comment]
@samuelt1 I'm glad Alex tried to give it a go 😉. Sorry you run into problems though. I'll double check this is all working for me. 

What's the error you're seeing now gulp is installed and also what versions of gulp and npm are you using?

**Comment by seadowg** [comment]
@samuelt1 Everything still working for me but the gulp/npm versions are very specific and the build process isn't that simple. I think the simplest solution for the moment is to stop Alex actually having to build the web component. To do this we can provide prebuilt assets that can then just be pushed.

**Comment by samuelt1** [comment]
YES! That would be AWESOME!!! Alex has been beating his head against walls left and right. He could give you an error, but there are like 20. He could fix one, but another 6 would arise. that would be awesome if you released a pre-built version that could just be deployed to PWS.

**Comment by seadowg** [comment]
@samuelt1 here's a package generated using the new process in #62 [postfacto.zip](https://github.com/Pivotal/postfacto/files/2163719/postfacto.zip). Let me know if it works for you!

**Comment by samuelt1** [comment]
Alex is now blissfully ignorant of the build process thank you!

**Comment by seadowg** [comment]
@samuelt1 awesome to hear! Thanks for being our guinea pig for the new package deploys. I'll be releasing this soon.
