### ISSUE TITLE
PWS deployment: bring down the memory footprint of the deployed `web` app

### ISSUE THREAD

**Issue by Kehrlann** [Pivotal/postfacto#70]
When deploying to CF, the API uses 256MB memory. However, the web app uses the default memory, which is 1GB on PWS. We can probably trim this down to 64MB or even 32MB (currently, when there are no requests, it uses 13MB of memory).

Thoughts ?

**Comment by seadowg** [comment]
I'd for sure be up for trimming this down. If you have a good idea of numbers I'd be happy to accept a PR 😀
