### ISSUE TITLE
Deployment to AWS Question

### ISSUE THREAD

**Issue by codeHatcher** [Pivotal/postfacto#71]
I see deployment specific to PWF PCS (first time I've heard of these before). Are there hosting agnostic instructions aside from using docker? If I follow local deployment instructions will that work or will that be less performant?

**Comment by seadowg** [comment]
@codeHatcher there isn't any reason you won't be able to get this working. Would love to hear about challenges/successes if you give it a go! 

We're definitely not looking to lock Postfacto in to any particular platform but it is definitely simpler to setup on Cloud Foundry for the moment as that was where postfacto.io was running.
