### ISSUE TITLE
Retroboard selfservice

### ISSUE THREAD

**Issue by tenjaa** [Pivotal/postfacto#76]
After I deployed postfacto sucessfully (thanks again for the support!), other teams started wanting to use it.
And I dont want to be the person who needs to create every board. Another thing is I do not want to be able to see all of their retro items.

Is there a way to achieve this?
One way would be to make an admin account public knowledge but I am not sure that I will like that..

**Comment by seadowg** [comment]
You can configure Google OAuth to let user's sign up with their Google account and create Retros. Docs on that are in the release but also here: https://github.com/Pivotal/postfacto/blob/master/deployment/INSTRUCTIONS.md#setting-up-google-oauth.
