### ISSUE TITLE
Limit user reactions

### ISSUE THREAD

**Issue by eddiewebb** [pivotal/postfacto#84]
Either a total reaction/votes limit per user, or at least a 1-vote-per-card limit.  Currently users can "game" the board by voting continuously for the same item.

I know that users are anonymous, but even a session based limit would prevent incidental extra votes, and leave explicitly malicious behavior for users to clear sessions to extra vote.

**Comment by liamdarmody** [comment]
Hi 👋 @eddiewebb - thanks for your suggestion!

I totally understand where you're coming from. Before getting into the technical constraints, I think it's worth giving some context as to why it's been built this way. The heart feature is supposed to mirror **+1s** in physical whiteboard retros. The great thing about **+1s** on the whiteboard is that the scale is extremely flexible. Some people might add a **+1** if they agree with the retro item. Others might add a **+100** if they **really agree** with the retro item. In any case, the ideal retro is one that gets through all the items on the board.

Some additional context can be found in these two Medium posts [here](https://builttoadapt.io/how-to-run-a-really-good-retrospective-8982bd839e16), and [here](https://medium.com/@nicolarushton/7-things-i-learned-about-retrospectives-while-building-postfacto-69863cc1ec41). I'll summarise the key points below:
- Retro is one practise that helps build a great team
- Talking about every item helps make sure everyone knows their voice is valued and equal
- Setting aside time each week purely for team communication and reflection builds a sense in the team that they can trust each other and that feedback is encouraged
- Getting through every retro item helps make sure everyone’s voice is heard
- These are the philosophies that have been driving product decisions for Postfacto

With these points in mind, I'm curious to dig into how you and your team are using the heart feature. Does your team use it to vote on retro items before the conversation? Is the conversation ordered by what has most votes? If so, I'd be curious to know if this leads to some retro items not being talked about?

If you have any suggestions about how we can balance the above philosophies, whilst solving your team's needs, we'd love to hear them! 🙌 🇲🇱

**Comment by eddiewebb** [comment]
This is the most well articulated response I've ever seen on a project. Thank you for taking the time.

We do use it as voting, not for things you agree with, but things you want to be discussed. Folks are allowed to vote for their own if they want, but we find once people put a topic out, most all get votes and discussed

**Comment by tlabeeuw** [comment]
I like the concept of hearts/+1's, but sometimes on particularly large teams, struggling, or time otherwise constrained teams, being able to have some voting and thus ordering of talked about items is helpful!

So maybe have two options:

* Hearts is unconstrained and unlimited. 
* Votes (🗳, ☑️ , or similar) is constrained to a retro setting to `n` votes per person total. Votes can be all put on one card or spread out however the voter wants. If `n = 0` then the Votes icon does not appear.
