### ISSUE TITLE
Create new retros without authentication

### ISSUE THREAD

**Issue by MichaelDBrown** [pivotal/postfacto#88]
The docs state: 

> In order for users to sign-up and create their own retros using the web UI, Postfacto needs Google OAuth setup. 

Some customers do not allow the use of Google OAuth and some don't even have any type of oauth providers. Is it possible to allow new retros to be created without authentication? Essentially allow self-service without a centralized admin creating the retro.

**Comment by MichaelDBrown** [comment]
This is most useful when postfacto is deployed inside an organization on pcf.

**Comment by seadowg** [comment]
@MichaelDBrown thanks for catching up about this in real life. Right now we're going to shelve this but are interested to hear more if this comes up as need for more people.
