### ISSUE TITLE
Ability to remove the video button

### ISSUE THREAD

**Issue by MichaelDBrown** [pivotal/postfacto#91]
A user should be able to create a retro with no video link and then no video button should appear on the retro.

**Comment by seadowg** [comment]
Assuming you're using the admin panel creation flow (correct me if not) you should have an Appear.in video link generated for you. Currently Postfacto always defaults to generating you a link if you delete it manually.

Are you experiencing a need to stop people from having a video link? I'm imagining some orgs might not want people using tools like Appear.in. Interesting to hear more!

**Comment by MichaelDBrown** [comment]
Corporate policy prevents them from using the Appear.in service. Yes, using the admin panel creation. There doesn't appear to be a way to not have a link created.

**Comment by seadowg** [comment]
Right that makes a lot of sense. I'll write acceptance and add this to our backlog.

**Comment by seadowg** [comment]
**ACCEPTANCE**

**GIVEN** I am Alex
**AND** I editing a Retro in the Admin panel
**AND** I tick "Disable Video"
**WHEN** I hit save
**AND** I visit the Retro
**THEN** there is no "Video" button to click on

@MichaelDBrown let me know if this sounds right
