### ISSUE TITLE
retro items disappeared after archive

### ISSUE THREAD

**Issue by shell-autonomic-sh** [pivotal/postfacto#94]
Hi:
    I'm a user of postfacto, I created an instance in PWS(pivotal web services). It's great. But I have a little problem. My retro items disappeared after archive. I mean, the action items still there, but nothing more. In the upper columns it just have "I'm glad that...", "I'm wondering about...", etc. Can you help me to identify what problem it is? Or maybe it's a feature I don't know.
    Any suggestion will be appreciated.

**Comment by seadowg** [comment]
Hey @shell-autonomic-sh! 👋

This is intended. Once you've "archived" a retro you can go to `Menu > View archives` and then select the date to view it again.
